const { PrismaClient } = require('@prisma/client');
const XLSX = require('xlsx');

const prisma = new PrismaClient();

async function runTests() {
  console.log('====================================================');
  console.log('🧪 RUNNING END-TO-END VERIFICATION TESTS');
  console.log('====================================================\n');

  // Test 1: Verify Seed Data & Multi-Company Structure
  console.log('Test 1: Verifying Multi-Company Setup...');
  const companies = await prisma.company.findMany();
  console.log(`✓ Found ${companies.length} companies:`, companies.map(c => `${c.code} (${c.nameTh})`).join(', '));
  if (companies.length < 2) throw new Error('Failed: Expected at least 2 companies');

  // Test 2: Verify Multi-Items per Subcontractor
  console.log('\nTest 2: Verifying Multi-Items per Subcontractor...');
  const job1 = await prisma.job.findFirst({
    where: { jobCode: 'CP1-JOB-202608-0001' },
    include: {
      subContracts: {
        include: {
          items: true,
          payments: true,
          subcontractor: true,
        }
      }
    }
  });

  if (!job1) throw new Error('Failed: Job 1 not found');
  const sc1 = job1.subContracts[0];
  console.log(`✓ Job: ${job1.jobCode} - ${job1.title}`);
  console.log(`✓ Subcontractor: ${sc1.subcontractor.name}`);
  console.log(`✓ Number of child items in 1 contract: ${sc1.items.length}`);
  sc1.items.forEach((it, i) => {
    console.log(`   ${i+1}. [${it.itemCode}] ${it.itemName}: ${it.quantity} ${it.unit} @ ฿${it.unitRate} = ฿${it.totalAmount}`);
  });
  console.log(`✓ Aggregated Contract Total: ฿${sc1.totalContractAmount}`);

  // Test 3: Verify Dynamic Payments & Overpayment Guard Math
  console.log('\nTest 3: Verifying Dynamic Installment Payments & Math...');
  const netContract = sc1.totalContractAmount + sc1.extraAmount - sc1.deductAmount;
  const paidTotal = sc1.payments.reduce((sum, p) => sum + p.amount, 0);
  const remaining = netContract - paidTotal;
  console.log(`✓ Base Contract: ฿${sc1.totalContractAmount} + Extra: ฿${sc1.extraAmount} - Deduct: ฿${sc1.deductAmount}`);
  console.log(`✓ Net Contract Amount: ฿${netContract}`);
  console.log(`✓ Paid So Far (${sc1.payments.length} installments): ฿${paidTotal}`);
  console.log(`✓ Remaining Balance: ฿${remaining}`);
  sc1.payments.forEach(p => {
    console.log(`   - Installment ${p.installmentNo}: Gross ฿${p.amount} - WHT 3% ฿${p.whtAmount} = Net ฿${p.netAmount} (Ref: ${p.refNo})`);
  });

  // Test 4: Price Benchmarking Logic
  console.log('\nTest 4: Verifying Price Benchmarking across Subcontractors...');
  const itemWood = await prisma.item.findUnique({
    where: { code: 'ITEM-WOOD-001' },
    include: {
      rateHistory: {
        include: { subcontractor: true }
      }
    }
  });

  const rates = itemWood.rateHistory.map(r => r.unitRate);
  const minRate = Math.min(...rates);
  const avgRate = rates.reduce((a, b) => a + b, 0) / rates.length;
  const lowestSub = itemWood.rateHistory.find(r => r.unitRate === minRate)?.subcontractor;

  console.log(`✓ Item: ${itemWood.code} - ${itemWood.name}`);
  console.log(`✓ Standard Rate: ฿${itemWood.standardRate}/${itemWood.unit}`);
  console.log(`✓ Lowest Contractor Rate: ฿${minRate}/${itemWood.unit} (Offered by: ${lowestSub.name})`);
  console.log(`✓ Average Rate across all contractors: ฿${avgRate.toFixed(2)}/${itemWood.unit}`);

  // Test 5: Subcontractor Quotation (Inverted header)
  console.log('\nTest 5: Verifying Subcontractor Quotation Generated by Company...');
  const qt = await prisma.subQuotation.findFirst({
    include: {
      company: true,
      subcontractor: true,
      items: true,
    }
  });
  console.log(`✓ Quotation: ${qt.quotationNo} (${qt.projectName})`);
  console.log(`✓ Vendor / Subcontractor (Issuer): ${qt.subcontractor.name} (Tax ID: ${qt.subcontractor.idCard})`);
  console.log(`✓ Client / Recipient: ${qt.company.nameTh} (Tax ID: ${qt.company.taxId})`);
  console.log(`✓ Subtotal: ฿${qt.subtotal} - WHT ${qt.whtRate}%: ฿${qt.whtAmount} = Grand Total: ฿${qt.grandTotal}`);

  console.log('\n====================================================');
  console.log('✅ ALL DATABASE & FUNCTIONAL VERIFICATIONS PASSED!');
  console.log('====================================================');
}

runTests()
  .catch(err => {
    console.error('❌ Test failed with error:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
